/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 52000ff212985dd6d2f818dce1684177)
interface __BaseEnv_Env {
	ARCHIVE: R2Bucket;
	DOWNLOAD_PREFIX: "d-7cb687993cfeb495e9719476afeb961e";
	R2_PREFIX: "public-image/desktop-compat-20260817/2ff8c68acb770b561834c014";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DOWNLOAD_PREFIX" | "R2_PREFIX">> {}
}
