import type {
  CodexAuditInvocationDetail,
  NativeImageAuditProjection,
  NativeRunDetail,
  RunDetail,
} from '../src/types';

/**
 * These are deliberately absent from the response objects below. They are only
 * used by fixture consumers to prove that the public contract stays path- and
 * raw-evidence-free.
 */
export const NATIVE_RUN_PRIVATE_SENTINELS = [
  'NIMG050F_RAW_THREAD_SENTINEL',
  'NIMG050F_RAW_CALL_SENTINEL',
  'NIMG050F_RAW_PATH_SENTINEL',
  'NIMG050F_RAW_PROMPT_SENTINEL',
  'NIMG050F_RAW_ACCOUNT_SENTINEL',
  '.codex-private',
] as const;

export const NATIVE_AUDIT_DETAIL_CREDENTIAL_SENTINELS = [
  'NIMG050F_AUTHORIZATION_SECRET',
  'NIMG050F_API_KEY_SECRET',
  'NIMG050F_ACCESS_TOKEN_SECRET',
  'NIMG050F_REFRESH_TOKEN_SECRET',
  'NIMG050F_COOKIE_SECRET',
  'NIMG050F_COPIED_AUTH_SECRET',
  'NIMG050F_ACCOUNT_SECRET',
] as const;

const PARENT_SHA256 = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
const BUSINESS_SHA256 = 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb';

const nativeSuccessProjection = {
  requested_model: 'gpt-5.6-luna',
  actual_model: 'gpt-5.6-luna',
  requested_reasoning_effort: 'low',
  actual_reasoning_effort: 'low',
  cli_version: 'codex-cli safe-version',
  binary_sha256: 'safe-binary-sha256',
  attempt: 1,
  terminal_state: 'result_received',
  retry: false,
  timeout: false,
  skip: false,
  fallback_used: false,
  failure_code: null,
  business_image: {
    png_valid: true,
    width: 1920,
    height: 1080,
    bytes: 2048,
    sha256: BUSINESS_SHA256,
  },
  normalization: {
    normalized: true,
    algorithm: 'native_slide_16x9_v1',
    operation: 'blurred_cover_aspect_fit',
    pillow_version: '12.1.1',
    parent_dimensions: [1672, 941],
    child_dimensions: [1920, 1080],
    parent_bytes: 1024,
    child_bytes: 2048,
    parent_sha256: PARENT_SHA256,
    child_sha256: BUSINESS_SHA256,
    derivation: {
      background: 'blurred_cover',
      foreground: 'uncropped_aspect_fit',
      parent_dimensions: [1672, 941],
      child_dimensions: [1920, 1080],
      parent_bytes: 1024,
      child_bytes: 2048,
      parent_sha256: PARENT_SHA256,
      child_sha256: BUSINESS_SHA256,
    },
  },
} as const satisfies NativeImageAuditProjection;

const nativeFailureProjection = {
  requested_model: 'gpt-5.6-luna',
  actual_model: 'gpt-5.6-luna',
  requested_reasoning_effort: 'low',
  actual_reasoning_effort: 'low',
  cli_version: 'codex-cli safe-version',
  binary_sha256: 'safe-binary-sha256',
  attempt: 1,
  terminal_state: 'failed',
  retry: false,
  timeout: false,
  skip: false,
  fallback_used: false,
  failure_code: 'image_call_binding_failed',
  normalization: {
    normalized: null,
    algorithm: null,
    operation: null,
    pillow_version: null,
    parent_dimensions: null,
    child_dimensions: null,
    parent_bytes: null,
    child_bytes: null,
    parent_sha256: null,
    child_sha256: null,
  },
} as const satisfies NativeImageAuditProjection;

export const nativeRunSuccessFixture = {
  id: 901,
  batch_id: 90,
  deck_id: 91,
  requirement_id: 92,
  color_id: 93,
  config_id: 94,
  created_at: '2026-07-24T00:00:00Z',
  engine: 'image',
  strategy: 'codex_native',
  status: 'completed',
  output_dir: null,
  design_principle_raw: null,
  design_principle_json: null,
  error_message: null,
  stage_artifacts: { native_image: nativeSuccessProjection },
  model_call_metadata: { native_image: nativeSuccessProjection },
  slides: [
    {
      id: 9011,
      run_id: 901,
      slide_id: 911,
      position: 1,
      status: 'completed',
      final_image_path: '/artifacts/runs/run-901/slide-01-business.png',
      conversation_id: null,
      raw_response: null,
      clean_html: null,
      html_path: null,
      screenshot_path: null,
      screenshot_path_source: null,
      xml_raw: null,
      xml_clean: null,
      error_message: null,
      stage_artifacts: { native_image: nativeSuccessProjection },
      seed_dependency: { native_image: nativeSuccessProjection },
    },
  ],
  codex_audit: {
    run_id: 901,
    status: 'completed',
    failure_count: 0,
    attempt_count: 1,
    per_slide_statuses: [{ run_slide_id: 9011, position: 1, status: 'completed', attempt_count: 1 }],
    invocation_count: 1,
    event_count: 1,
    error_event_count: 0,
    invocations: [
      {
        id: 9101,
        run_id: 901,
        run_slide_id: 9011,
        stage_id: 'native-image',
        role: 'image_generator',
        attempt: 1,
        status: 'result_received',
        sandbox: null,
        model: 'gpt-5.6-luna',
        reasoning_effort: 'low',
        event_count: 1,
        error_event_count: 0,
        usage: {},
        exit_code: 0,
        error_message: null,
        started_at: '2026-07-24T00:00:00Z',
        ended_at: '2026-07-24T00:00:01Z',
        elapsed_ms: 1000,
        events: [
          {
            sequence: 1,
            event_type: 'thread.started',
            item_type: 'function_call',
            is_error: false,
            observed_at: '2026-07-24T00:00:00Z',
            event_timestamp: '2026-07-24T00:00:00Z',
          },
        ],
        native_image: nativeSuccessProjection,
      },
    ],
  },
} as const satisfies NativeRunDetail;

export const nativeRunFailureFixture = {
  id: 902,
  batch_id: 90,
  deck_id: 91,
  requirement_id: 92,
  color_id: 93,
  config_id: 94,
  created_at: '2026-07-24T00:00:00Z',
  engine: 'image',
  strategy: 'codex_native',
  status: 'failed',
  output_dir: null,
  design_principle_raw: null,
  design_principle_json: null,
  error_message: null,
  stage_artifacts: { native_image: nativeFailureProjection },
  model_call_metadata: { native_image: nativeFailureProjection },
  slides: [
    {
      id: 9021,
      run_id: 902,
      slide_id: 912,
      position: 1,
      status: 'failed',
      final_image_path: null,
      conversation_id: null,
      raw_response: null,
      clean_html: null,
      html_path: null,
      screenshot_path: null,
      screenshot_path_source: null,
      xml_raw: null,
      xml_clean: null,
      error_message: null,
      stage_artifacts: { native_image: nativeFailureProjection },
    },
  ],
  codex_audit: {
    run_id: 902,
    status: 'failed',
    failure_count: 1,
    attempt_count: 1,
    per_slide_statuses: [{ run_slide_id: 9021, position: 1, status: 'failed', attempt_count: 1 }],
    invocation_count: 1,
    event_count: 1,
    error_event_count: 0,
    invocations: [
      {
        id: 9201,
        run_id: 902,
        run_slide_id: 9021,
        stage_id: 'native-image',
        role: 'image_generator',
        attempt: 1,
        status: 'failed',
        sandbox: null,
        model: 'gpt-5.6-luna',
        reasoning_effort: 'low',
        event_count: 1,
        error_event_count: 0,
        usage: {},
        exit_code: null,
        error_message: null,
        started_at: '2026-07-24T00:00:00Z',
        ended_at: '2026-07-24T00:00:01Z',
        elapsed_ms: 1000,
        events: [
          {
            sequence: 1,
            event_type: 'thread.started',
            item_type: 'function_call',
            is_error: false,
            observed_at: '2026-07-24T00:00:00Z',
            event_timestamp: '2026-07-24T00:00:00Z',
          },
        ],
        native_image: nativeFailureProjection,
      },
    ],
  },
} as const satisfies NativeRunDetail;

/**
 * Preview characterization fixtures mirror the actual isolated C022 API
 * projection. The Python fixed oracle independently joins that public shape
 * back to its current-schema DB, so these serialized fixtures cannot close the
 * partial contract by themselves.
 */
export const nativeRunPageTwoFirstFixture = {
  id: 903,
  batch_id: 90,
  deck_id: 91,
  deck_title: '中国历史',
  requirement_id: 92,
  color_id: 93,
  config_id: 94,
  created_at: '2026-07-30T00:00:00Z',
  engine: 'image',
  strategy: 'image_3_0',
  status: 'running',
  slides: [
    {
      id: 9034,
      run_id: 903,
      slide_id: 914,
      position: 4,
      slide_title: '第四页',
      slide_type: 'content',
      status: 'running',
      has_displayable_artifact: false,
    },
    {
      id: 9032,
      run_id: 903,
      slide_id: 912,
      position: 2,
      slide_title: '第二页',
      slide_type: 'content',
      status: 'completed',
      final_image_path: '/artifacts/runs/run-903/02.png',
      has_displayable_artifact: true,
    },
    {
      id: 9031,
      run_id: 903,
      slide_id: 911,
      position: 1,
      slide_title: '封面',
      slide_type: 'cover',
      status: 'running',
      has_displayable_artifact: false,
    },
    {
      id: 9033,
      run_id: 903,
      slide_id: 913,
      position: 3,
      slide_title: '第三页',
      slide_type: 'content',
      status: 'running',
      has_displayable_artifact: false,
    },
  ],
} as const satisfies RunDetail;

export const nativeRunPartialFixture = {
  ...nativeRunPageTwoFirstFixture,
  status: 'completed_with_failures',
  completed_at: '2026-07-30T00:01:00Z',
  error_message: 'image_3_0_fanout_partial',
  slides: [
    {
      id: 9032,
      run_id: 903,
      slide_id: 912,
      position: 2,
      slide_title: '第二页',
      slide_type: 'content',
      status: 'completed',
      final_image_path: '/artifacts/runs/run-903/02.png',
      has_displayable_artifact: true,
    },
    {
      id: 9034,
      run_id: 903,
      slide_id: 914,
      position: 4,
      slide_title: '第四页',
      slide_type: 'content',
      status: 'completed',
      final_image_path: '/artifacts/runs/run-903/04.png',
      has_displayable_artifact: true,
    },
    {
      id: 9031,
      run_id: 903,
      slide_id: 911,
      position: 1,
      slide_title: '封面',
      slide_type: 'cover',
      status: 'completed',
      final_image_path: '/artifacts/runs/run-903/01.png',
      has_displayable_artifact: true,
    },
    {
      id: 9033,
      run_id: 903,
      slide_id: 913,
      position: 3,
      slide_title: '第三页',
      slide_type: 'content',
      status: 'failed',
      error_message: 'position-three-render-failed',
      has_displayable_artifact: false,
    },
  ],
} as const satisfies RunDetail;

/** Loaded only by an explicit Run/invocation expansion, never in the Run response. */
export const nativeAuditDetailFixture = {
  run_id: 901,
  invocation_id: 9101,
  lineage: {
    run_id: 901,
    run_slide_id: 9011,
    stage_id: 'native-image',
    attempt: 1,
    invocation_id: 9101,
    session: {
      bytes: 321,
      sha256: 'canonical-session-sha256',
    },
    call: {
      id: 'NIMG050F_AUDIT_IMAGEGEN_CALL',
      arguments_sha256: 'imagegen-arguments-sha256',
    },
  },
  prompt: 'NIMG050F business prompt: make an auditable 16:9 business slide image.',
  assistant_output: 'NIMG050F assistant output: completed the business image request.',
  tool_calls: [
    {
      event_sequence: 2,
      kind: 'function_call',
      name: 'imagegen',
      call_id: 'NIMG050F_AUDIT_IMAGEGEN_CALL',
      payload: {
        type: 'function_call',
        name: 'imagegen',
        call_id: 'NIMG050F_AUDIT_IMAGEGEN_CALL',
      },
    },
  ],
  imagegen_calls: [
    {
      event_sequence: 2,
      kind: 'function_call',
      name: 'imagegen',
      call_id: 'NIMG050F_AUDIT_IMAGEGEN_CALL',
      payload: {
        type: 'image_generation_end',
        name: 'imagegen',
        call_id: 'NIMG050F_AUDIT_IMAGEGEN_CALL',
        status: 'completed',
        revised_prompt: 'NIMG050F revised prompt: retain the approved business slide.',
      },
    },
  ],
  errors: {
    invocation_error: null,
    metadata_error: null,
    event_errors: [],
  },
  jsonl: {
    raw: {
      sha256: 'raw-jsonl-sha256',
    },
    observed: {
      sha256: 'observed-jsonl-sha256',
    },
    canonical_session: {
      bytes: 321,
      sha256: 'canonical-session-sha256',
    },
  },
  metadata: {
    actual_model: 'gpt-5.6-sol',
    terminal_state: 'result_received',
    business_image: { sha256: 'business-image-sha256', bytes: 321 },
  },
} as const satisfies CodexAuditInvocationDetail;
